# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 15:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import nece.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('benefits', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, nece.managers.TranslationMixin),
        ),
    ]
